# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60529718e060cd9429684d98d67fcb32598c219dadb09b6908f1d07da2c0acd802bf1eb38ad859cb02190640ed515678b3e1991009928d4d5d5487e304468c03

test:
  secret_key_base: 18a1279b93c083c325b2a8b3a54992f3141885598065e732bc6366f791041e4a7adf7fa65df5c48af033ec49e6de0d1ab6b195f7a08df5eab8026e02abf70f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
